src = Split("""
	BotOptions.cpp
	CommandHandler.cpp
	DUMIIFinger.cpp
	IRCBot.cpp
	Message.cpp
	OPify.cpp
	Say.cpp
	Socket.cpp
	Time.cpp
	UserStats.cpp
	main.cpp
""")

libs = Split("""
	boost_program_options
	boost_system
	boost_thread
	pthread
""")

ccflags = Split("""
	-std=gnu++0x
	-Wall
	-g
""")

Program("Bot", src, LIBS=libs, CCFLAGS=ccflags)
